import type { Veterinary } from "../_components/types";
export const mockVets: Veterinary[] = [
  {
    id: "1",
    name: "SF Pet Hospital",
    rating: 4.9,
    reviewCount: 328,
    distance: "0.8 mi",
    address: "123 Market St",
    city: "San Francisco",
    state: "CA",
    services: ["Emergency", "Surgery", "Dental"],
    hours: "24/7 Emergency",
    isOpen: true,
    emergency: true,
    phone: "(415) 555-0123",
    coordinates: { lat: 37.7749, lng: -122.4194 },
  },
  {
    id: "2",
    name: "Golden Gate Vet Clinic",
    rating: 4.7,
    reviewCount: 215,
    distance: "1.2 mi",
    address: "456 Oak St",
    city: "San Francisco",
    state: "CA",
    services: ["Wellness", "Vaccination", "Grooming"],
    hours: "8AM - 8PM",
    isOpen: true,
    emergency: false,
    phone: "(415) 555-0456",
    coordinates: { lat: 37.7849, lng: -122.4294 },
  },
  {
    id: "3",
    name: "Bay Area Animal Care",
    rating: 4.8,
    reviewCount: 412,
    distance: "2.1 mi",
    address: "789 Mission St",
    city: "San Francisco",
    state: "CA",
    services: ["Surgery", "Dental", "Boarding"],
    hours: "7AM - 10PM",
    isOpen: true,
    emergency: false,
    phone: "(415) 555-0789",
    coordinates: { lat: 37.7649, lng: -122.4094 },
  },
  {
    id: "4",
    name: "Paws & Claws Veterinary",
    rating: 4.6,
    reviewCount: 189,
    distance: "3.5 mi",
    address: "321 Valencia St",
    city: "San Francisco",
    state: "CA",
    services: ["Wellness", "Emergency", "X-Ray"],
    hours: "9AM - 6PM",
    isOpen: false,
    emergency: false,
    phone: "(415) 555-0321",
    coordinates: { lat: 37.7549, lng: -122.4394 },
  },
];
