import type { Veterinary } from '../types';

export const mockVets: Veterinary[] = [
  {
    id: '1',
    name: 'Улсын Нэгдүгээр Төв Эмнэлэг',
    rating: 4.5,
    reviewCount: 328,
    address: 'Сүхбаатар дүүрэг, 1-р хороо',
    services: ['Яаралтай тусламж', 'Мэс засал', 'Оношилгоо', 'Лаборатори'],
    hours: '24 цаг',
    isOpen: true,
    emergency: true,
    phone: '+976 11 311515',
    category: 'emneleg',
    lat: 47.9212,
    lng: 106.9057,
  },
  {
    id: '2',
    name: 'Интермед Эмнэлэг',
    rating: 4.6,
    reviewCount: 215,
    address: 'Баянгол дүүрэг, 3-р хороо',
    services: ['Эх барих', 'Дотор', 'Хүүхэд', 'Нялхас'],
    hours: '08:00 - 18:00',
    isOpen: true,
    emergency: false,
    phone: '+976 11 313131',
    category: 'emneleg',
    lat: 47.9189,
    lng: 106.9012,
  },
  {
    id: '3',
    name: 'Эх Нялхсын Төв',
    rating: 4.4,
    reviewCount: 412,
    address: 'Хан-Уул дүүрэг, 2-р хороо',
    services: ['Эх барих', 'Нялхас', 'Лаборатори', 'УЗ оношилгоо'],
    hours: '09:00 - 17:00',
    isOpen: false,
    emergency: false,
    phone: '+976 11 323232',
    category: 'klinik',
    lat: 47.9156,
    lng: 106.9089,
  },
  {
    id: '4',
    name: 'Яаралтай Тусламжийн Төв',
    rating: 4.8,
    reviewCount: 189,
    address: 'Сүхбаатар дүүрэг, 5-р хороо',
    services: ['Яаралтай тусламж', 'Мэс засал', 'Оношилгоо'],
    hours: '24 цаг',
    isOpen: true,
    emergency: true,
    phone: '+976 105',
    category: 'yaaraltai',
    lat: 47.9198,
    lng: 106.9123,
  },
  {
    id: '5',
    name: 'СЭЖ-ийн Эмийн сан',
    rating: 4.3,
    reviewCount: 95,
    address: 'Баянгол дүүрэг, 1-р хороо',
    services: ['Эмийн борлуулалт', 'Зөвлөгөө'],
    hours: '08:00 - 22:00',
    isOpen: true,
    emergency: false,
    phone: '+976 11 345678',
    category: 'emiin_san',
    lat: 47.9178,
    lng: 106.8956,
  },
];
